scrape_configs:
- job_name: 'spring-boot-actuator-app'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: ['spring-boot-actuator-app:8080']
